"""identidade visual da fazenda

Revision ID: 10caebc78743
Revises: f8e601466013
Create Date: 2026-09-05 07:13:59.127701
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '10caebc78743'
down_revision: str | None = 'f8e601466013'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fazendas', sa.Column('cor_primaria', sa.String(length=7), nullable=True))
    op.add_column('fazendas', sa.Column('cor_destaque', sa.String(length=7), nullable=True))
    op.add_column('fazendas', sa.Column('cor_fundo', sa.String(length=7), nullable=True))
    op.add_column('fazendas', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fazendas', 'logo_url')
    op.drop_column('fazendas', 'cor_fundo')
    op.drop_column('fazendas', 'cor_destaque')
    op.drop_column('fazendas', 'cor_primaria')
    # ### end Alembic commands ###
