"""modelagem inicial

Revision ID: 60b1a091d02e
Revises: 
Create Date: 2026-09-04 21:23:51.363977
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '60b1a091d02e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fazendas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('proprietario', sa.String(length=160), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('plano', sa.String(length=40), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('lotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('data_formacao', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_fazenda_id'), 'lotes', ['fazenda_id'], unique=False)
    op.create_table('usuario_fazenda',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('fazenda_id', sa.UUID(), nullable=False),
    sa.Column('papel', sa.Enum('tecnico', 'cliente', 'admin', name='papel'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'fazenda_id', name='uq_usuario_fazenda')
    )
    op.create_index(op.f('ix_usuario_fazenda_fazenda_id'), 'usuario_fazenda', ['fazenda_id'], unique=False)
    op.create_index(op.f('ix_usuario_fazenda_usuario_id'), 'usuario_fazenda', ['usuario_id'], unique=False)
    op.create_table('animais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.UUID(), nullable=False),
    sa.Column('brinco', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('raca', sa.String(length=80), nullable=True),
    sa.Column('porte', sa.String(length=40), nullable=True),
    sa.Column('brinco_mae', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('peso_nascimento', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('lote_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'vendido', 'morto', 'transferido', name='status_animal'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animais_fazenda_id'), 'animais', ['fazenda_id'], unique=False)
    op.create_index('ix_animais_fazenda_lote', 'animais', ['fazenda_id', 'lote_id'], unique=False)
    op.create_index('uq_animal_brinco_ativo', 'animais', ['fazenda_id', 'brinco'], unique=True, postgresql_where=sa.text("status = 'ativo'"))
    op.create_table('animal_brinco_historico',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('brinco', sa.String(length=20), nullable=False),
    sa.Column('vinculado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('desvinculado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_brinco_historico_animal_id'), 'animal_brinco_historico', ['animal_id'], unique=False)
    op.create_index('ix_brinco_historico_brinco', 'animal_brinco_historico', ['brinco'], unique=False)
    op.create_table('pesagens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fazenda_id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('observacao_texto', sa.Text(), nullable=True),
    sa.Column('observacao_audio_url', sa.String(length=500), nullable=True),
    sa.Column('status_transcricao', sa.Enum('pendente', 'processando', 'concluida', 'falhou', name='status_transcricao'), nullable=True),
    sa.Column('tecnico_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('coletado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pesagens_animal_data', 'pesagens', ['animal_id', 'data'], unique=False)
    op.create_index(op.f('ix_pesagens_animal_id'), 'pesagens', ['animal_id'], unique=False)
    op.create_index('ix_pesagens_fazenda_data', 'pesagens', ['fazenda_id', 'data'], unique=False)
    op.create_index(op.f('ix_pesagens_fazenda_id'), 'pesagens', ['fazenda_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pesagens_fazenda_id'), table_name='pesagens')
    op.drop_index('ix_pesagens_fazenda_data', table_name='pesagens')
    op.drop_index(op.f('ix_pesagens_animal_id'), table_name='pesagens')
    op.drop_index('ix_pesagens_animal_data', table_name='pesagens')
    op.drop_table('pesagens')
    op.drop_index('ix_brinco_historico_brinco', table_name='animal_brinco_historico')
    op.drop_index(op.f('ix_animal_brinco_historico_animal_id'), table_name='animal_brinco_historico')
    op.drop_table('animal_brinco_historico')
    op.drop_index('uq_animal_brinco_ativo', table_name='animais', postgresql_where=sa.text("status = 'ativo'"))
    op.drop_index('ix_animais_fazenda_lote', table_name='animais')
    op.drop_index(op.f('ix_animais_fazenda_id'), table_name='animais')
    op.drop_table('animais')
    op.drop_index(op.f('ix_usuario_fazenda_usuario_id'), table_name='usuario_fazenda')
    op.drop_index(op.f('ix_usuario_fazenda_fazenda_id'), table_name='usuario_fazenda')
    op.drop_table('usuario_fazenda')
    op.drop_index(op.f('ix_lotes_fazenda_id'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('fazendas')
    # ### end Alembic commands ###

    # O autogenerate cria os tipos ENUM junto com as tabelas, mas não os remove
    # no downgrade — sem isto, um downgrade seguido de upgrade falha com
    # "type already exists".
    for tipo in ("status_transcricao", "status_animal", "papel"):
        op.execute(f"DROP TYPE IF EXISTS {tipo}")
