"""superusuario e soft delete

Revision ID: 682ebecaeba1
Revises: 60b1a091d02e
Create Date: 2026-09-04 22:10:25.196063
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '682ebecaeba1'
down_revision: str | None = '60b1a091d02e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animais', sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_animais_desativado_em'), 'animais', ['desativado_em'], unique=False)
    op.add_column('fazendas', sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_fazendas_desativado_em'), 'fazendas', ['desativado_em'], unique=False)
    op.add_column('lotes', sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_lotes_desativado_em'), 'lotes', ['desativado_em'], unique=False)
    op.add_column('pesagens', sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_pesagens_desativado_em'), 'pesagens', ['desativado_em'], unique=False)
    op.add_column('usuario_fazenda', sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_usuario_fazenda_desativado_em'), 'usuario_fazenda', ['desativado_em'], unique=False)
    # server_default é obrigatório aqui: a coluna é NOT NULL e a tabela pode já
    # ter linhas. O default fica só para o backfill; o valor em uso vem do model.
    op.add_column(
        'usuarios',
        sa.Column('admin_master', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('usuarios', 'admin_master', server_default=None)
    op.add_column('usuarios', sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_usuarios_desativado_em'), 'usuarios', ['desativado_em'], unique=False)
    # Preserva o dado antes de largar a coluna antiga: quem estava inativo
    # continua inativo, agora com data.
    op.execute("UPDATE usuarios SET desativado_em = now() WHERE ativo IS FALSE")
    op.drop_column('usuarios', 'ativo')
    # ### end Alembic commands ###

    # O autogenerate não compara a cláusula WHERE de índice parcial, então a
    # troca precisa ser escrita à mão: o brinco passa a poder ser reaproveitado
    # também quando o animal é desativado, não só quando sai do rebanho.
    op.drop_index('uq_animal_brinco_ativo', table_name='animais')
    op.create_index(
        'uq_animal_brinco_ativo',
        'animais',
        ['fazenda_id', 'brinco'],
        unique=True,
        postgresql_where=sa.text("status = 'ativo' AND desativado_em IS NULL"),
    )


def downgrade() -> None:
    op.drop_index('uq_animal_brinco_ativo', table_name='animais')
    op.create_index(
        'uq_animal_brinco_ativo',
        'animais',
        ['fazenda_id', 'brinco'],
        unique=True,
        postgresql_where=sa.text("status = 'ativo'"),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'usuarios',
        sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False,
                  server_default=sa.true()),
    )
    op.execute("UPDATE usuarios SET ativo = FALSE WHERE desativado_em IS NOT NULL")
    op.alter_column('usuarios', 'ativo', server_default=None)
    op.drop_index(op.f('ix_usuarios_desativado_em'), table_name='usuarios')
    op.drop_column('usuarios', 'desativado_em')
    op.drop_column('usuarios', 'admin_master')
    op.drop_index(op.f('ix_usuario_fazenda_desativado_em'), table_name='usuario_fazenda')
    op.drop_column('usuario_fazenda', 'desativado_em')
    op.drop_index(op.f('ix_pesagens_desativado_em'), table_name='pesagens')
    op.drop_column('pesagens', 'desativado_em')
    op.drop_index(op.f('ix_lotes_desativado_em'), table_name='lotes')
    op.drop_column('lotes', 'desativado_em')
    op.drop_index(op.f('ix_fazendas_desativado_em'), table_name='fazendas')
    op.drop_column('fazendas', 'desativado_em')
    op.drop_index(op.f('ix_animais_desativado_em'), table_name='animais')
    op.drop_column('animais', 'desativado_em')
    # ### end Alembic commands ###
