"""limites de alerta por fazenda

Revision ID: f8e601466013
Revises: 3e0c66336837
Create Date: 2026-09-05 04:36:30.910812
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f8e601466013'
down_revision: str | None = '3e0c66336837'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default porque a coluna é NOT NULL e a tabela já tem linhas. Os
    # valores são os que estavam fixos no código até aqui, para nenhuma fazenda
    # existente mudar de comportamento com a migration.
    op.add_column(
        'fazendas',
        sa.Column('gmd_meta', sa.Numeric(precision=4, scale=3), nullable=False,
                  server_default='0.500'),
    )
    op.add_column(
        'fazendas',
        sa.Column('dias_sem_pesagem', sa.Integer(), nullable=False, server_default='45'),
    )
    op.alter_column('fazendas', 'gmd_meta', server_default=None)
    op.alter_column('fazendas', 'dias_sem_pesagem', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fazendas', 'dias_sem_pesagem')
    op.drop_column('fazendas', 'gmd_meta')
    # ### end Alembic commands ###
